name: generate contribution snake

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: LALALOLO123
          outputs: |
            dist/github-snake.svg?color_snake=%2300b8ff&color_dots=%23eef2f6,%23a9f5d5,%2354e8b0,%2300ff9f,%2300b8ff
            dist/github-snake-dark.svg?color_snake=%2300ff9f&color_dots=%231f2630,%23103a2c,%2317724f,%2300ff9f,%2300b8ff

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
